sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8.3'
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run semantic-release
  - npm publish
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
